name: atreeon_get_child_size
description: A widget that returns the size of the child object.  The [onChange] callback will run everytime the widget's size has changed.
repository: https://github.com/atreeon/atreeon_get_child_size
homepage: https://atreeon.com
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
